# Dependencies
markdown: kramdown
highlighter: pygments

# Premalinks
permalink: pretty

# Special
#include: ['.htaccess']

# Site Setup
# private hosting with htaccess file
#url: http://gonsie.myrpi.org

title: XPDES
tagline: 'The eXtreme Parallel Discrete-Event Simulation Consortium'
description: 'The eXtreme Parallel Discrete-Event Simulation Consortium'

author:
  name: 'Elsa Gonsiorowski'
  url: http://www.gonsie.com

# number of posts that appear on a page
paginate: 1

# Sidebar Vars
#version: 1.0
github:
  repo: https://github.com/XPDES

# Exclude Files
exclude: ['README.md','people/template.md']
