# Dependencies
markdown: redcarpet
pygments: true

# Premalinks
permalink: pretty

# Special
#include: ['.htaccess']

# Site Setup
#url: http://gonsie.myrpi.org

title: XPDES
tagline: 'The eXtreme Parallel Discrete-Event Simulation Consortium'
description: 'The eXtreme Parallel Discrete-Event Simulation Consortium'



author:
  name: 'Elsa Gonsiorowski'
  url: http://gonsie.com

paginate: 1

# Sidebar Vars
#version: 1.0
github:
  repo: https://github.com/XPDES
